a:
	g++ -o a a.cpp -Wall -Wextra -pedantic

b:
	g++ -o b b.cpp -Wall -Wextra -pedantic

c:
	g++ -o c c.cpp -Wall -Wextra -pedantic

d:
	g++ -o d d.cpp -Wall -Wextra -pedantic

e:
	g++ -o e e.cpp -Wall -Wextra -pedantic

f:
	g++ -o f f.cpp -Wall -Wextra -pedantic

ra: 
	rm a

rb: 
	rm b

rc: 
	rm c

rd: 
	rm d

re: 
	rm e

rf: 
	rm f
